[workspace]

resolver = "2"

members = [
    "reductionml-core",
    "reductionml-cli",
    "reductionml-python",
    "utils/reductionml-docs-extension"
]

default-members = [
    "reductionml-core",
    "reductionml-cli",
]

[profile.release]
lto = "thin"
